export const CONTENT_UPLOAD_REQUEST = "CONTENT_UPLOAD_REQUEST";
export const CONTENT_UPLOAD_SUCCESS = "CONTENT_UPLOAD_SUCCESS";
export const CONTENT_UPLOAD_FAIL = "CONTENT_UPLOAD_FAIL";

export const CONTENT_FETCH_ALL_REQUEST = "CONTENT_FETCH_ALL_REQUEST";
export const CONTENT_FETCH_ALL_SUCCESS = "CONTENT_FETCH_ALL_SUCCESS";
export const CONTENT_FETCH_ALL_FAIL = "CONTENT_FETCH_ALL_FAIL";

export const CONTENT_FETCH_BY_ID_REQUEST = "CONTENT_FETCH_BY_ID_REQUEST";
export const CONTENT_FETCH_BY_ID_SUCCESS = "CONTENT_FETCH_BY_ID_SUCCESS";
export const CONTENT_FETCH_BY_ID_FAIL = "CONTENT_FETCH_BY_ID_FAIL";

export const CONTENT_DELETE_REQUEST = "CONTENT_DELETE_REQUEST";
export const CONTENT_DELETE_SUCCESS = "CONTENT_DELETE_SUCCESS";
export const CONTENT_DELETE_FAIL = "CONTENT_DELETE_FAIL";