// Constants for action types
export const ENROLLMENT_REQUEST = 'ENROLLMENT_REQUEST';
export const ENROLLMENT_SUCCESS = 'ENROLLMENT_SUCCESS';
export const ENROLLMENT_FAILURE = 'ENROLLMENT_FAILURE';

export const GET_ENROLLMENTS_BY_STUDENT_REQUEST = 'GET_ENROLLMENTS_BY_STUDENT_REQUEST';
export const GET_ENROLLMENTS_BY_STUDENT_SUCCESS = 'GET_ENROLLMENTS_BY_STUDENT_SUCCESS';
export const GET_ENROLLMENTS_BY_STUDENT_FAILURE = 'GET_ENROLLMENTS_BY_STUDENT_FAILURE';

export const GET_ENROLLMENTS_BY_COURSE_REQUEST = 'GET_ENROLLMENTS_BY_COURSE_REQUEST';
export const GET_ENROLLMENTS_BY_COURSE_SUCCESS = 'GET_ENROLLMENTS_BY_COURSE_SUCCESS';
export const GET_ENROLLMENTS_BY_COURSE_FAILURE = 'GET_ENROLLMENTS_BY_COURSE_FAILURE';