export const STUDYPLAN_CREATE_REQUEST = 'STUDYPLAN_CREATE_REQUEST';
export const STUDYPLAN_CREATE_SUCCESS = 'STUDYPLAN_CREATE_SUCCESS';
export const STUDYPLAN_CREATE_FAIL = 'STUDYPLAN_CREATE_FAIL';

export const STUDYPLAN_DETAILS_REQUEST = 'STUDYPLAN_DETAILS_REQUEST';
export const STUDYPLAN_DETAILS_SUCCESS = 'STUDYPLAN_DETAILS_SUCCESS';
export const STUDYPLAN_DETAILS_FAIL = 'STUDYPLAN_DETAILS_FAIL';

export const STUDENT_STUDYPLANS_REQUEST = 'STUDENT_STUDYPLANS_REQUEST';
export const STUDENT_STUDYPLANS_SUCCESS = 'STUDENT_STUDYPLANS_SUCCESS';
export const STUDENT_STUDYPLANS_FAIL = 'STUDENT_STUDYPLANS_FAIL';

export const STUDYPLAN_RESET = 'STUDYPLAN_RESET';
