export const CREATE_STUDY_REQUEST_REQUEST = 'CREATE_STUDY_REQUEST_REQUEST';
export const CREATE_STUDY_REQUEST_SUCCESS = 'CREATE_STUDY_REQUEST_SUCCESS';
export const CREATE_STUDY_REQUEST_FAIL = 'CREATE_STUDY_REQUEST_FAIL';
export const CREATE_STUDY_REQUEST_RESET = 'CREATE_STUDY_REQUEST_RESET';